### ISSUE TITLE
Can you open the "issues" or "discussions" in the repo : "LoRA-Merger-ComfyUI"? 

### ISSUE THREAD

**Issue by ClothingAI** [larsupb/comfyui-joycaption#1]
Please?
Thanks.
I wanted to ask a question there, for example, does it work with flux loras? But yeah its good to have an open platform to ask questions and communicate with other users sometimes.

**Comment by larsupb** [comment]
Okay, done. :-)

**Comment by ClothingAI** [comment]
> Okay, done. :-)

Great, I actually got some answers in the meantime, but you can leave it open maybe I or others will have questions in the future? ;)
